---
title: "Simple MCMC in R"
output: html_notebook
theme: journal
highlight: pygments
---

### Import some libraries that we will need.
```{r}
library(ggplot2)
library(grid)
library(gridExtra)
```

### Create some fake data.
```{r}
# model parameters
N <- 50
m <- 0.05
b <- 0.3
alpha <- -1
l <- 0.1
sigma <- 0.5
sigma_noise <- 0.05

# simulate data
yerr <- sigma_noise + 0.05 * runif(n=N, min=0, max=1)
n <- yerr * rnorm(n=N, mean=0, sd=1)
t <- runif(n=N, min=-5, max=5)
s <- b + m*t + alpha * exp(-(t-l)**2/2/sigma**2)
data <- s + n

# plot data
qplot(t, data) + geom_errorbar(aes(ymin = data - yerr, ymax = data + yerr))
```

### Define likelihood, prior, and posterior.
```{r}
# likelihood function
log.likelihood <- function(params){
  m <- params[1]
  b <- params[2]
  alpha <- params[3]
  l <- params[4]
  sigma <- params[5]

  mean <- b + m*t + alpha * exp(-(t-l)**2/2/sigma**2)
  lnlike <- dnorm(data, mean=mean, sd=yerr, log=TRUE)
  return(sum(lnlike))
}

# prior function
log.prior <- function(params){

  pmin <- c(-10, -10, -10, -5, 0.1)
  pmax <- c(10, 10, 10, 5, 3)

  lpr = dunif(params, min=pmin, max=pmax, log=TRUE)
  return(sum(lpr))
}

# posterior function
log.posterior <- function(params){
  return(log.likelihood(params)+log.prior(params))
}
```

### Let's setup the proposal and simple MCMC sampler.
```{r}
# simple MCMC
run.mcmc <- function(p0, N){
  chain <- array(dim=c(N+1,length(p0)))
  chain[1,] <- p0
  for (ii in 1:N){

    # proposal
    q <- proposal(chain[ii,])

    # posterior ratio
    ldiff <- log.posterior(q) - log.posterior(chain[ii,])
    if (ldiff >= log(runif(1))){
      chain[ii+1,] <- q
    } else{
      chain[ii+1,] = chain[ii,]
    }
  }
  return(chain)
}
```

### Initialize parameters and sample!
```{r}
params <- c(0.01, 0.2, -0.5, 0.2, 0.2)
jsig = c(0.1, 0.1, 0.1, 0.1, 0.1)
print(log.likelihood(params))
print(log.prior(params))
proposal(params)

# run sampler for 100000 samples
N <- 100000
chain <- run.mcmc(params, N)
```

### Let's make a crude triangle plot
```{r}
# make plots
nparams <- length(params)
burn <- 5000
pars <- c('m', 'b', 'alpha', 'l', 'sigma')
truths <- c(m, b, alpha, l, sigma)
par(mfrow=c(nparams, nparams), omi=c(0.5,0.3,0,0), plt=c(0.1,0.9,0,0.7))
for (ii in 1:nparams){
  for (jj in 1:nparams){
    if (ii==jj){
      hist(chain[-(1:burn),ii], nclass=30, xlab=pars[ii], main=NULL)
      abline(v = truths[ii], col="red", lwd=2)
    } else if (ii<jj){
      plot(0,type='n',axes=FALSE,ann=FALSE)
    } else{
      plot(x=chain[-(1:burn),ii], y=chain[-(1:burn),jj], xlab=pars[ii], ylab=pars[jj],
      main=NULL, col=rgb(0, 0, 0, alpha = 0.05))
      points(x=truths[ii], y=truths[jj], col='red', pch=4, lwd=2)
    }
  }
}
```



